version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/EXTs/EXT-Background"
    schedule:
      interval: "weekly"
    target-branch: "dev"
