name: "MagicMirror² (develop) and MMM-GoogleAssistant build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install MMM-GoogleAssistant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MagicMirror² (develop)
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror
          ref: develop

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout MMM-GoogleAssistant
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-GoogleAssistant

      - name: Install MMM-GoogleAssistant
        run: npm install
        working-directory: MagicMirror/modules/MMM-GoogleAssistant
        continue-on-error: false
